/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaconfig;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ApplicationContext appContext = new AnnotationConfigApplicationContext(AppConfig.class);
        HelloWorld obj = (HelloWorld) appContext.getBean("helloBean");
        obj.printHelloWorld("bla");
    }
}
